using System.Collections.Concurrent;
using System.Diagnostics;
using System.Numerics;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Cache;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;

namespace AddedObjectRemover;

public static class Program
{
    private static Lazy<Settings> _lazySettings = new();

    /// <summary>Base game plugins never count as "other mods". Creation Club plugins deliberately are not listed.</summary>
    private static readonly ModKey[] BaseGamePlugins =
    [
        ModKey.FromNameAndExtension("Skyrim.esm"),
        ModKey.FromNameAndExtension("Update.esm"),
        ModKey.FromNameAndExtension("Dawnguard.esm"),
        ModKey.FromNameAndExtension("HearthFires.esm"),
        ModKey.FromNameAndExtension("Dragonborn.esm"),
    ];

    /// <summary>Z coordinate removed objects are moved to (standard "safe disable" depth).</summary>
    private const float RemovedZ = -30000f;

    /// <summary>The player reference (always enabled), used as Enable Parent of removed objects that had one.</summary>
    private static readonly FormKey PlayerRef = FormKey.Factory("000014:Skyrim.esm");

    public static async Task<int> Main(string[] args)
    {
        // Optional "--log-file <path>" (not a Synthesis option): mirrors console output to a file.
        // Useful when the patcher is launched directly by MO2, where output can't be redirected.
        using var logFile = ConsoleLogFile.TryStart(ref args);
        try
        {
            return await SynthesisPipeline.Instance
                .SetAutogeneratedSettings(
                    "Settings",
                    "settings.json",
                    out _lazySettings)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "AddedObjectRemover.esp")
                .Run(args);
        }
        catch (Exception ex) when (logFile != null)
        {
            logFile.WriteToFileOnly(ex.ToString());
            throw;
        }
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        var totalTimer = Stopwatch.StartNew();
        Console.WriteLine("=== Added Object Remover ===");

        var config = CreateConfig(state, _lazySettings.Value);
        if (config == null) return;
        PrintConfig(config);

        // 1. One pass over every winning placed record (REFR, ACHR and all placed trap/hazard/projectile types).
        var phaseTimer = Stopwatch.StartNew();
        // Only the target plugin's own file is walked here, to know which spaces can matter.
        var targetSpaceInfo = CollectTargetSpaceKeys(state, config.Target);
        var scan = ScanPlacedRecords(state, config, targetSpaceInfo.SpaceKeys, targetSpaceInfo.OverriddenByTarget);
        Console.WriteLine(
            $"Scanned {scan.RecordsScanned:N0} placed records in {phaseTimer.Elapsed.TotalSeconds:F1}s: "
            + $"{scan.Targets.Count:N0} {config.Target} objects to check, "
            + $"{scan.OthersBySpace.Values.Sum(x => x.Count):N0} objects from other mods.");
        if (scan.TargetsOverriddenLater > 0)
        {
            Console.WriteLine($"  Ignored {scan.TargetsOverriddenLater:N0} {config.Target} objects whose winning version comes from a later plugin.");
        }
        if (scan.TargetsDisabledOrWithoutPlacement > 0)
        {
            Console.WriteLine($"  Ignored {scan.TargetsDisabledOrWithoutPlacement:N0} {config.Target} objects that are initially disabled or have no valid position.");
        }
        if (scan.OthersOverriddenByTarget > 0)
        {
            Console.WriteLine($"  Ignored {scan.OthersOverriddenByTarget:N0} other-mod objects that {config.Target} itself overrides.");
        }

        if (scan.Targets.Count == 0)
        {
            Console.WriteLine("Nothing to check. No changes made.");
            return;
        }

        var parallelOptions = new ParallelOptions { MaxDegreeOfParallelism = Environment.ProcessorCount };
        Console.WriteLine($"Using {parallelOptions.MaxDegreeOfParallelism} threads.");

        // 2. Index other mods' objects, but only in spaces that contain target objects.
        phaseTimer.Restart();
        var bounds = new ObjectBoundsProvider(state, config.UseNifBounds, config.Verbose);
        var invisibleOthers = new InvisibleCounter();
        var spaces = BuildOtherSpaces(scan, bounds, invisibleOthers);
        Console.WriteLine(
            $"Indexed {spaces.Values.Sum(s => s.Count):N0} other objects in {spaces.Count:N0} cells/worldspaces "
            + $"in {phaseTimer.Elapsed.TotalSeconds:F1}s.");

        // 3. Bounds warm-up: every target base object's bounds, in parallel. Other objects' bounds
        // are only resolved later, lazily, for objects a too-close query actually turns up.
        phaseTimer.Restart();
        bounds.PrepareArchives();
        var targetBases = scan.Targets
            .Select(t => t.Base)
            .OfType<BaseRef>()
            .DistinctBy(b => b.FormKey)
            .ToList();
        bounds.WarmUp(targetBases, parallelOptions);
        bounds.PrintMessages();
        Console.WriteLine($"Bounds warm-up: {targetBases.Count:N0} target base objects in {phaseTimer.Elapsed.TotalSeconds:F1}s.");

        // 3.5. Exclude other-mod objects the target plugin appears to have replaced in place
        // (same position, similar size) from proximity checks entirely.
        phaseTimer.Restart();
        var replacements = ExcludeReplacedObjects(scan, spaces, bounds, config, parallelOptions);
        bounds.PrintMessages();
        if (config.IgnoreReplacedObjects)
        {
            Console.WriteLine(
                $"Replacement matching: {replacements.ExcludedCount:N0} other-mod objects excluded in {phaseTimer.Elapsed.TotalSeconds:F1}s.");
        }

        // 4. Exact too-close test for every target object.
        phaseTimer.Restart();
        var hits = FindTooCloseTargets(scan.Targets, spaces, bounds, config.Multiplier, parallelOptions);
        bounds.PrintMessages();
        Console.WriteLine(
            $"Found {hits.Count:N0} of {scan.Targets.Count:N0} {config.Target} objects too close to other mods' objects "
            + $"in {phaseTimer.Elapsed.TotalSeconds:F1}s.");
        PrintInvisibleOthers(invisibleOthers, config.Verbose);

        // 5. Decide which to keep.
        var removals = new List<Removal>();
        var keptTooClose = new List<int>();
        var keptAsReferenced = 0;
        foreach (var hit in hits)
        {
            var target = scan.Targets[hit.TargetIndex];
            var keepReason = config.SkipReferenced ? GetKeepReason(target, scan.TargetReferences) : null;
            if (keepReason != null)
            {
                keptAsReferenced++;
                keptTooClose.Add(hit.TargetIndex);
                Console.WriteLine($"  Kept {Describe(target.Record)} in {scan.SpaceNames[target.SpaceKey]}: {keepReason}.");
                continue;
            }
            removals.Add(new Removal(hit.TargetIndex, hit.Other, TouchedIndex: null));
        }
        var removedTooClose = removals.Count;

        // 6. Touching clusters: target objects touching removed target objects go too.
        if (config.RemoveTouching && removals.Count > 0)
        {
            if (!config.UseNifBounds)
            {
                Console.WriteLine("Touching objects: skipped, mesh (NIF) measurement is disabled and touching needs mesh geometry.");
            }
            else
            {
                var touch = FindTouchingClusters(scan, removals, keptTooClose, bounds, config, parallelOptions);
                bounds.PrintMessages();
                removals.AddRange(touch.Removals);
                keptAsReferenced += touch.KeptAsReferenced;
                PrintTouchStats(touch);
            }
        }

        // 7. Write overrides (single-threaded, after all computation has finished).
        phaseTimer.Restart();
        var placedByList = new Dictionary<object, Dictionary<FormKey, IPlaced>>(ReferenceEqualityComparer.Instance);
        var enableParentsReplaced = 0;
        foreach (var removal in removals)
        {
            if (RemoveObject(scan.Targets[removal.TargetIndex], state.PatchMod, placedByList)) enableParentsReplaced++;
        }
        Console.WriteLine($"Wrote {removals.Count:N0} overrides in {phaseTimer.Elapsed.TotalSeconds:F1}s.");
        if (enableParentsReplaced > 0)
        {
            Console.WriteLine(
                $"  {enableParentsReplaced:N0} removed objects had an Enable Parent; it was replaced by the player "
                + "with \"opposite of parent\" so they stay disabled.");
        }

        if (config.Verbose)
        {
            foreach (var removal in removals) LogRemoval(bounds, scan, removal);
        }

        PrintBoundsStats(bounds, config.UseNifBounds);
        if (config.Verbose) PrintSpaceSummary(scan, spaces, removals);

        Console.WriteLine(
            $"Removed {removals.Count:N0} objects ({removedTooClose:N0} too close, "
            + $"{removals.Count - removedTooClose:N0} touching a removed object); "
            + $"kept {keptAsReferenced:N0} referenced objects.");
        Console.WriteLine($"Done in {totalTimer.Elapsed.TotalSeconds:F1}s.");
    }

    // ------------------------------------------------------------------
    // Configuration
    // ------------------------------------------------------------------

    private sealed record RunConfig(
        ModKey Target,
        HashSet<ModKey> IgnoredOrigins,
        IReadOnlyList<ModKey> ExcludedPlugins,
        IReadOnlyList<ModKey> TargetMasters,
        bool ExcludeTargetMasters,
        float Multiplier,
        bool UseNifBounds,
        bool SkipReferenced,
        bool RemoveTouching,
        float TouchTolerance,
        float VoxelSize,
        bool Verbose,
        bool IgnoreReplacedObjects,
        float ReplacementPositionTolerance,
        float ReplacementSizeSimilarity);

    private static RunConfig? CreateConfig(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, Settings settings)
    {
        if (string.IsNullOrWhiteSpace(settings.TargetPlugin))
        {
            Console.WriteLine("No target plugin set. No changes made.");
            return null;
        }
        if (!ModKey.TryFromNameAndExtension(settings.TargetPlugin.Trim(), out var target))
        {
            Console.WriteLine($"Target plugin '{settings.TargetPlugin}' is not a valid plugin file name. No changes made.");
            return null;
        }
        var targetListing = state.LoadOrder.ListedOrder.FirstOrDefault(listing => listing.ModKey == target);
        if (targetListing == null)
        {
            Console.WriteLine($"Target plugin {target} is not in the load order. No changes made.");
            return null;
        }

        var ignored = new HashSet<ModKey>(BaseGamePlugins) { target, state.PatchMod.ModKey };

        var excluded = new List<ModKey>();
        foreach (var name in settings.ExcludedPlugins)
        {
            if (string.IsNullOrWhiteSpace(name)) continue;
            if (ModKey.TryFromNameAndExtension(name.Trim(), out var key))
            {
                excluded.Add(key);
                ignored.Add(key);
            }
            else
            {
                Console.WriteLine($"Warning: excluded plugin '{name}' is not a valid plugin file name and was ignored.");
            }
        }

        var masters = new List<ModKey>();
        if (settings.ExcludeTargetMasters)
        {
            if (targetListing.Mod is { } targetMod)
            {
                foreach (var master in targetMod.MasterReferences)
                {
                    masters.Add(master.Master);
                    ignored.Add(master.Master);
                }
            }
            else
            {
                Console.WriteLine($"Warning: could not read {target} to find its masters.");
            }
        }

        var multiplier = settings.Multiplier;
        if (!float.IsFinite(multiplier) || multiplier < 0)
        {
            Console.WriteLine($"Warning: multiplier {settings.Multiplier} is invalid; using 0.");
            multiplier = 0;
        }

        var touchTolerance = settings.TouchTolerance;
        if (!float.IsFinite(touchTolerance) || touchTolerance < 0)
        {
            Console.WriteLine($"Warning: touch tolerance {settings.TouchTolerance} is invalid; using 0.");
            touchTolerance = 0;
        }

        var voxelSize = settings.VoxelSize;
        if (!float.IsFinite(voxelSize) || voxelSize < 1)
        {
            Console.WriteLine($"Warning: voxel size {settings.VoxelSize} is invalid (minimum 1); using 1.");
            voxelSize = 1;
        }

        var replacementPositionTolerance = settings.ReplacementPositionTolerance;
        if (!float.IsFinite(replacementPositionTolerance) || replacementPositionTolerance < 0)
        {
            Console.WriteLine($"Warning: replacement position tolerance {settings.ReplacementPositionTolerance} is invalid; using 0.");
            replacementPositionTolerance = 0;
        }

        var replacementSizeSimilarity = settings.ReplacementSizeSimilarity;
        if (!float.IsFinite(replacementSizeSimilarity))
        {
            Console.WriteLine($"Warning: replacement size similarity {settings.ReplacementSizeSimilarity} is invalid; using 0.75.");
            replacementSizeSimilarity = 0.75f;
        }
        else if (replacementSizeSimilarity is < 0 or > 1)
        {
            var clamped = Math.Clamp(replacementSizeSimilarity, 0f, 1f);
            Console.WriteLine($"Warning: replacement size similarity {settings.ReplacementSizeSimilarity} is out of range 0-1; using {clamped}.");
            replacementSizeSimilarity = clamped;
        }

        return new RunConfig(
            Target: target,
            IgnoredOrigins: ignored,
            ExcludedPlugins: excluded,
            TargetMasters: masters,
            ExcludeTargetMasters: settings.ExcludeTargetMasters,
            Multiplier: multiplier,
            UseNifBounds: settings.UseNifBounds,
            SkipReferenced: settings.SkipReferencedObjects,
            RemoveTouching: settings.RemoveTouchingObjects,
            TouchTolerance: touchTolerance,
            VoxelSize: voxelSize,
            Verbose: settings.VerboseLogging,
            IgnoreReplacedObjects: settings.IgnoreReplacedObjects,
            ReplacementPositionTolerance: replacementPositionTolerance,
            ReplacementSizeSimilarity: replacementSizeSimilarity);
    }

    private static void PrintConfig(RunConfig config)
    {
        static string Join(IReadOnlyList<ModKey> keys) => keys.Count == 0 ? "(none)" : string.Join(", ", keys);

        Console.WriteLine($"Target plugin: {config.Target}");
        Console.WriteLine($"Multiplier: {config.Multiplier}");
        Console.WriteLine($"Excluded plugins: {Join(config.ExcludedPlugins)}");
        Console.WriteLine(config.ExcludeTargetMasters
            ? $"Excluded masters of target: {Join(config.TargetMasters)}"
            : "Masters of target are not excluded.");
        Console.WriteLine($"Bounds source: {(config.UseNifBounds ? "NIF mesh, OBND fallback" : "OBND only")}");
        Console.WriteLine($"Keep referenced objects: {config.SkipReferenced}; verbose: {config.Verbose}");
        Console.WriteLine(config.RemoveTouching
            ? $"Remove touching objects: tolerance {config.TouchTolerance}, voxel size {config.VoxelSize}"
            : "Touching objects are not removed.");
        Console.WriteLine(config.IgnoreReplacedObjects
            ? $"Ignore replaced objects: position tolerance {config.ReplacementPositionTolerance}, size similarity {config.ReplacementSizeSimilarity}"
            : "Same-position replacement matching is disabled (objects the target plugin itself overrides are still ignored).");
    }

    // ------------------------------------------------------------------
    // Scanning
    // ------------------------------------------------------------------

    /// <summary>
    /// A target-plugin object that may be removed. Only plain data plus the winning context of its
    /// cell is kept; the override is written through that cell context (see <see cref="RemoveObject"/>).
    /// </summary>
    private sealed record TargetObject(
        IPlacedGetter Record,
        IModContext<ISkyrimMod, ISkyrimModGetter, ICell, ICellGetter> WinningCell,
        bool InPersistentList,
        FormKey SpaceKey,
        FormKey CellKey,
        string? CellName,
        PlacedTransform Transform,
        BaseRef? Base,
        bool IsTeleportDoor);

    /// <summary>Compact snapshot of another mod's placed object (winning version).</summary>
    private readonly record struct OtherObject(
        FormKey FormKey,
        ModKey WinningMod,
        string? EditorId,
        BaseRef? Base,
        Vector3 Position,
        P3Float Rotation,
        float Scale,
        bool IsPrimitive);

    /// <summary>A too-close target (index into ScanResult.Targets) and the first other object found.</summary>
    private readonly record struct Hit(int TargetIndex, OtherObject Other);

    /// <summary>
    /// A target object to remove (index into ScanResult.Targets): either too close to
    /// <paramref name="Other"/>, or touching the removed target <paramref name="TouchedIndex"/>.
    /// </summary>
    private sealed record Removal(int TargetIndex, OtherObject? Other, int? TouchedIndex);

    private sealed class ScanResult
    {
        public List<TargetObject> Targets { get; } = [];
        public Dictionary<FormKey, List<OtherObject>> OthersBySpace { get; } = new();
        public Dictionary<FormKey, string> SpaceNames { get; } = new();

        /// <summary>Target FormKey -> why another placed object depends on it (first reason found).</summary>
        public Dictionary<FormKey, string> TargetReferences { get; } = new();

        public int RecordsScanned { get; set; }
        public int TargetsOverriddenLater { get; set; }
        public int TargetsDisabledOrWithoutPlacement { get; set; }

        /// <summary>Other-mod objects excluded because the target plugin itself overrides them (rule 1).</summary>
        public int OthersOverriddenByTarget { get; set; }
    }

    /// <summary>
    /// Single pass over every placed record of the load order.
    ///
    /// Why this shape: Mutagen has no IPlaced case in SkyrimModCommon.EnumerateMajorRecordContexts,
    /// so enumerating IPlaced contexts falls back to InterfaceEnumerationHelper, which runs one full
    /// enumeration per implementing registration (APlacedTrap, PlacedNpc, PlacedObject): every
    /// cell tree, exterior block/subblock and (re-created) worldspace TopCell of every plugin is
    /// walked three times. Enumerating concrete types once each would still be 3+ walks (PlacedObject,
    /// PlacedNpc and each placed trap/projectile type). Instead, each mod's cell tree is walked
    /// exactly once via EnumerateMajorRecordContexts&lt;ICell, ICellGetter&gt;: for ICellGetter
    /// Mutagen yields every interior cell (CellBlocks/SubBlocks) and every worldspace TopCell and
    /// exterior cell (Blocks/SubBlocks) without descending into their children
    /// (ModContextExt: TypeMatch.Match), and this method then reads each cell's Persistent and
    /// Temporary lists itself.
    ///
    /// Mods are visited in priority order (highest first), so the first time a FormKey is seen is
    /// its winning override, exactly like Mutagen's WinningContextOverrides (a deleted winner still
    /// claims its FormKey, so an older version never takes its place). The same holds for cells:
    /// the first context seen for a cell FormKey is its winning override, which is what Mutagen's
    /// own placed-record context would resolve (linkCache.Resolve&lt;ICellGetter&gt;) before adding
    /// the override, so it is kept for cells in target spaces and used for removal.
    /// </summary>
    private static ScanResult ScanPlacedRecords(
        IPatcherState<ISkyrimMod, ISkyrimModGetter> state,
        RunConfig config,
        IReadOnlySet<FormKey> targetSpaceKeys,
        IReadOnlySet<FormKey> overriddenByTarget)
    {
        var scan = new ScanResult();
        var seenRecords = new HashSet<FormKey>();
        var winningCells = new Dictionary<FormKey, IModContext<ISkyrimMod, ISkyrimModGetter, ICell, ICellGetter>>();

        foreach (var listing in state.LoadOrder.PriorityOrder)
        {
            if (listing.Mod is not { } mod) continue;
            var modKey = listing.ModKey;

            foreach (var cellContext in mod.EnumerateMajorRecordContexts<ICell, ICellGetter>(state.LinkCache))
            {
                var cell = cellContext.Record;
                var (spaceKey, spaceRecord) = GetCellSpace(cellContext);
                var inTargetSpace = targetSpaceKeys.Contains(spaceKey);
                if (inTargetSpace) winningCells.TryAdd(cell.FormKey, cellContext);

                if (cell.Persistent.Count == 0 && cell.Temporary.Count == 0) continue;

                for (var list = 0; list < 2; list++)
                {
                    var persistent = list == 0;
                    foreach (var record in persistent ? cell.Persistent : cell.Temporary)
                    {
                        if (!seenRecords.Add(record.FormKey)) continue; // A higher-priority mod already won.
                        scan.RecordsScanned++;
                        if (record.IsDeleted) continue;

                        if (config.SkipReferenced)
                        {
                            CollectTargetReferences(record, config.Target, scan.TargetReferences);
                        }

                        var origin = record.FormKey.ModKey;
                        var isTarget = origin == config.Target;
                        if (isTarget)
                        {
                            // Only objects the target plugin still "owns": not changed by any later plugin.
                            // This also covers the patch mod itself: if an earlier patcher in the same
                            // Synthesis run already overrode this object, the winning mod is the patch
                            // mod, not the target, so it is treated the same as any other later override.
                            if (modKey != config.Target)
                            {
                                scan.TargetsOverriddenLater++;
                                continue;
                            }
                        }
                        else if (config.IgnoredOrigins.Contains(origin))
                        {
                            continue;
                        }
                        else if (overriddenByTarget.Contains(record.FormKey))
                        {
                            // The target plugin itself overrides this FormKey (its own cell tree
                            // holds a copy of it), so it is a replacement, not an "other mod" object,
                            // no matter which plugin currently wins it.
                            scan.OthersOverriddenByTarget++;
                            if (config.Verbose)
                            {
                                var winner = modKey == origin ? string.Empty : $" (winning override in {modKey})";
                                Console.WriteLine(
                                    $"  Ignored other-mod object overridden by {config.Target}: "
                                    + $"{Describe(record.FormKey, record.EditorID)} from {origin}{winner}.");
                            }
                            continue;
                        }

                        if (IsInitiallyDisabled(record)
                            || record.Placement is not { } placement
                            || !Geometry.IsWithinLimits(Geometry.ToVector(placement.Position)))
                        {
                            if (isTarget) scan.TargetsDisabledOrWithoutPlacement++;
                            continue;
                        }

                        // Neither target objects nor indexed other objects can exist outside
                        // target spaces (targets define them), so nothing else is needed there.
                        if (!inTargetSpace) continue;

                        var position = Geometry.ToVector(placement.Position);
                        var scale = NormalizeScale(record.Scale);
                        var baseRef = GetBase(record);

                        if (isTarget)
                        {
                            // Space names are only ever displayed for target objects, so the string is
                            // only built here, once per space.
                            if (!scan.SpaceNames.ContainsKey(spaceKey))
                            {
                                scan.SpaceNames[spaceKey] = BuildSpaceName(spaceRecord);
                            }

                            scan.Targets.Add(new TargetObject(
                                Record: record,
                                WinningCell: winningCells[cell.FormKey],
                                InPersistentList: persistent,
                                SpaceKey: spaceKey,
                                CellKey: cell.FormKey,
                                CellName: config.Verbose && cell.FormKey != spaceKey ? Describe(cell) : null,
                                Transform: new PlacedTransform(position, Geometry.RotationFromEuler(placement.Rotation), scale),
                                Base: baseRef,
                                IsTeleportDoor: record is IPlacedObjectGetter { TeleportDestination: not null }));
                        }
                        else
                        {
                            if (!scan.OthersBySpace.TryGetValue(spaceKey, out var others))
                            {
                                others = [];
                                scan.OthersBySpace[spaceKey] = others;
                            }
                            others.Add(new OtherObject(
                                record.FormKey,
                                modKey,
                                config.Verbose ? record.EditorID : null,
                                baseRef,
                                position,
                                placement.Rotation,
                                scale,
                                record is IPlacedObjectGetter { Primitive: not null }));
                        }
                    }
                }
            }
        }

        return scan;
    }

    private static bool IsInitiallyDisabled(IPlacedGetter record) =>
        (record.MajorRecordFlagsRaw & (int)SkyrimMajorRecord.SkyrimMajorRecordFlag.InitiallyDisabled) != 0;

    private static float NormalizeScale(float? scale) =>
        scale is { } s && float.IsFinite(s) && s > 0 ? s : 1f;

    /// <summary>
    /// Comparison space of a cell yielded by the cell enumeration: its worldspace for exterior cells
    /// (including the worldspace's persistent TopCell, whose context parent is the worldspace),
    /// otherwise the interior cell itself.
    /// </summary>
    private static (FormKey SpaceKey, IMajorRecordGetter SpaceRecord) GetCellSpace(
        IModContext<ISkyrimMod, ISkyrimModGetter, ICell, ICellGetter> cellContext)
    {
        for (var current = cellContext.Parent; current != null; current = current.Parent)
        {
            if (current.Record is IWorldspaceGetter worldspace)
            {
                return (worldspace.FormKey, worldspace);
            }
        }
        return (cellContext.Record.FormKey, cellContext.Record);
    }

    private static string BuildSpaceName(IMajorRecordGetter spaceRecord) => spaceRecord switch
    {
        IWorldspaceGetter worldspace => $"worldspace {Describe(worldspace)}",
        ICellGetter cell => $"interior {Describe(cell)}",
        _ => Describe(spaceRecord),
    };

    /// <summary>
    /// Result of <see cref="CollectTargetSpaceKeys"/>: the spaces that can contain a target object,
    /// plus the FormKeys of every placed record the target plugin itself overrides (a record present
    /// in the target plugin's own cell tree whose FormKey originates from another plugin).
    /// </summary>
    private sealed record TargetSpaceInfo(HashSet<FormKey> SpaceKeys, HashSet<FormKey> OverriddenByTarget);

    /// <summary>
    /// Cheaply collects the set of spaces (worldspace or interior cell FormKeys) that contain at
    /// least one placed record created by the target plugin, by walking only the target plugin's
    /// own cell tree once. Used to avoid indexing other mods' objects in spaces that can never
    /// contain a target object. The same pass also collects every FormKey the target plugin
    /// overrides (regardless of which plugin ends up winning it), so such records are never treated
    /// as "other mods'" objects: the target plugin replaced them itself.
    /// </summary>
    private static TargetSpaceInfo CollectTargetSpaceKeys(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, ModKey target)
    {
        var keys = new HashSet<FormKey>();
        var overridden = new HashSet<FormKey>();
        var listing = state.LoadOrder.ListedOrder.FirstOrDefault(l => l.ModKey == target);
        if (listing?.Mod is not { } mod) return new TargetSpaceInfo(keys, overridden);

        foreach (var cellContext in mod.EnumerateMajorRecordContexts<ICell, ICellGetter>(state.LinkCache))
        {
            var cell = cellContext.Record;
            var hasTargetRecord = false;
            for (var list = 0; list < 2; list++)
            {
                foreach (var record in list == 0 ? cell.Persistent : cell.Temporary)
                {
                    if (record.FormKey.ModKey == target)
                    {
                        hasTargetRecord = true;
                    }
                    else
                    {
                        overridden.Add(record.FormKey);
                    }
                }
            }
            if (hasTargetRecord)
            {
                keys.Add(GetCellSpace(cellContext).SpaceKey);
            }
        }
        return new TargetSpaceInfo(keys, overridden);
    }

    /// <summary>Base object of any placed record type, with the base link's own record type.</summary>
    private static BaseRef? GetBase(IPlacedGetter record) => record switch
    {
        IPlacedObjectGetter placedObject => ToBaseRef(placedObject.Base),
        IPlacedNpcGetter placedNpc => ToBaseRef(placedNpc.Base),
        IPlacedHazardGetter hazard => ToBaseRef(hazard.Hazard),
        IPlacedArrowGetter arrow => ToBaseRef(arrow.Projectile),
        IPlacedBarrierGetter barrier => ToBaseRef(barrier.Projectile),
        IPlacedBeamGetter beam => ToBaseRef(beam.Projectile),
        IPlacedConeGetter cone => ToBaseRef(cone.Projectile),
        IPlacedFlameGetter flame => ToBaseRef(flame.Projectile),
        IPlacedMissileGetter missile => ToBaseRef(missile.Projectile),
        IPlacedTrapGetter trap => ToBaseRef(trap.Projectile),
        _ => null,
    };

    /// <summary>
    /// <typeparamref name="TGetter"/> is the link's declared target type (e.g. IPlaceableObjectGetter,
    /// INpcGetter, IHazardGetter, IProjectileGetter), used later for narrowly typed resolution.
    /// </summary>
    private static BaseRef? ToBaseRef<TGetter>(IFormLinkGetter<TGetter> link)
        where TGetter : class, IMajorRecordGetter =>
        link.IsNull ? null : new BaseRef(link.FormKey, typeof(TGetter));

    private static FormKey? LinkKey(IFormLinkGetter link) => link.IsNull ? null : link.FormKey;

    /// <summary>
    /// Records target-plugin objects that this record depends on: as Enable Parent, Linked
    /// Reference, Activate Parent, destination of its door teleport, or through any other form
    /// link of the record. Links to non-placed records are recorded too but never looked up.
    /// </summary>
    private static void CollectTargetReferences(IPlacedGetter record, ModKey target, Dictionary<FormKey, string> references)
    {
        void Add(IFormLinkGetter link, string relation)
        {
            if (LinkKey(link) is not { } key || key.ModKey != target || key == record.FormKey) return;
            if (references.ContainsKey(key)) return;
            references[key] = $"{relation} of {record.FormKey}";
        }

        if (record.EnableParent is { } enableParent)
        {
            Add(enableParent.Reference, "Enable Parent");
        }

        IReadOnlyList<ILinkedReferencesGetter>? linkedReferences = record switch
        {
            IPlacedObjectGetter placedObject => placedObject.LinkedReferences,
            IPlacedNpcGetter placedNpc => placedNpc.LinkedReferences,
            IAPlacedTrapGetter placedTrap => placedTrap.LinkedReferences,
            _ => null,
        };
        if (linkedReferences != null)
        {
            foreach (var linked in linkedReferences)
            {
                Add(linked.Reference, "Linked Reference");
            }
        }

        if (record is IPlacedObjectGetter { TeleportDestination: { } destination })
        {
            Add(destination.Door, "teleport destination of door");
        }

        var activateParents = record switch
        {
            IPlacedObjectGetter placedObject => placedObject.ActivateParents,
            IPlacedNpcGetter placedNpc => placedNpc.ActivateParents,
            IAPlacedTrapGetter placedTrap => placedTrap.ActivateParents,
            _ => null,
        };
        if (activateParents != null)
        {
            foreach (var parent in activateParents.Parents)
            {
                Add(parent.Reference, "Activate Parent");
            }
        }

        foreach (var link in record.EnumerateFormLinks())
        {
            Add(link, "referenced by a link");
        }
    }

    // ------------------------------------------------------------------
    // Too-close test
    // ------------------------------------------------------------------

    /// <summary>
    /// Margin (game units) added to a target's search AABB when querying the grid, to compensate
    /// for indexing other objects by their cheap raw position rather than their (possibly
    /// mesh-offset) true bounds center. One exterior cell width is a generous bound in practice.
    /// </summary>
    private const float OtherObjectSearchMargin = 4096f;

    /// <summary>
    /// Other-mod objects of one space, indexed by their raw position only - no bounds/NIF lookup
    /// at build time. Each object's true bounds center (rotation matrix, cached base bounds, maybe a
    /// mesh read) is computed at most once, lazily, the first time a query turns the object up
    /// (<see cref="GetBoundsCenter"/>), so objects that are never candidates never cost a mesh read.
    ///
    /// Objects whose base is invisible (<see cref="ObjectBoundsProvider.GetInvisibleReason"/>) are
    /// found the same lazy way and then never match.
    ///
    /// Thread-safe: the center is written before its state is published with an interlocked
    /// store, and read only after a load sees the state. Two threads measuring the same object
    /// concurrently write identical values, and only the one that publishes the state counts it.
    /// </summary>
    private sealed class OtherSpace
    {
        private const int NotMeasured = 0;
        private const int Visible = 1;
        private const int Invisible = 2;

        private readonly OtherObject[] _objects;
        private readonly ObjectBoundsProvider _bounds;
        private readonly InvisibleCounter _invisible;
        private readonly Vector3[] _centers;
        private readonly int[] _state;

        /// <summary>
        /// 0/1 per object: set (via <see cref="TryExclude"/>) when the object is judged a
        /// same-position/same-size replacement of some target object (rule 2). Excluded objects are
        /// still indexed in <see cref="Grid"/> (needed as replacement candidates) but never match in
        /// the too-close test.
        /// </summary>
        private readonly int[] _excluded;

        public OtherSpace(IReadOnlyList<OtherObject> objects, ObjectBoundsProvider bounds, InvisibleCounter invisible)
        {
            _objects = objects.ToArray();
            _bounds = bounds;
            _invisible = invisible;
            _centers = new Vector3[_objects.Length];
            _state = new int[_objects.Length];
            _excluded = new int[_objects.Length];
            var points = new Vector3[_objects.Length];
            for (var i = 0; i < points.Length; i++)
            {
                points[i] = Geometry.IsFinite(_objects[i].Position) ? _objects[i].Position : Vector3.Zero;
            }
            Grid = SpatialGrid.FromPoints(points);
        }

        public SpatialGrid Grid { get; }

        public int Count => _objects.Length;

        public OtherObject this[int index] => _objects[index];

        /// <summary>Marks the object as a replacement. Thread-safe; returns true only the first time.</summary>
        public bool TryExclude(int index) => Interlocked.CompareExchange(ref _excluded[index], 1, 0) == 0;

        public bool IsExcluded(int index) => Volatile.Read(ref _excluded[index]) != 0;

        /// <summary>
        /// World-space bounds center of a visible object; false (and no center) for an invisible one.
        /// </summary>
        public bool TryGetVisibleCenter(int index, out Vector3 center)
        {
            var state = Volatile.Read(ref _state[index]);
            if (state == NotMeasured) state = Measure(index);
            center = _centers[index];
            return state == Visible;
        }

        private int Measure(int index)
        {
            ref readonly var other = ref _objects[index];
            var reason = _bounds.GetInvisibleReason(other.Base, other.IsPrimitive);
            int state;
            if (reason != null)
            {
                state = Invisible;
            }
            else
            {
                var transform = new PlacedTransform(other.Position, Geometry.RotationFromEuler(other.Rotation), other.Scale);
                var point = Geometry.WorldBoundsCenter(_bounds.GetLocalBox(other.Base), transform);
                _centers[index] = Geometry.IsFinite(point) ? point : other.Position;
                state = Visible;
            }

            if (Interlocked.CompareExchange(ref _state[index], state, NotMeasured) == NotMeasured && reason != null)
            {
                _invisible.Add(reason);
            }
            return state;
        }
    }

    /// <summary>Thread-safe count of other objects ignored as invisible, per reason.</summary>
    private sealed class InvisibleCounter
    {
        private readonly ConcurrentDictionary<string, int> _byReason = new(StringComparer.Ordinal);

        public void Add(string reason) => _byReason.AddOrUpdate(reason, 1, (_, count) => count + 1);

        public IReadOnlyList<KeyValuePair<string, int>> Snapshot() =>
            _byReason.OrderByDescending(kv => kv.Value).ThenBy(kv => kv.Key, StringComparer.Ordinal).ToList();
    }

    /// <summary>
    /// One <see cref="OtherSpace"/> per space containing target objects (empty if it has no other
    /// objects). The scan's per-space lists are released afterwards.
    /// </summary>
    private static Dictionary<FormKey, OtherSpace> BuildOtherSpaces(
        ScanResult scan,
        ObjectBoundsProvider bounds,
        InvisibleCounter invisible)
    {
        var spaces = new Dictionary<FormKey, OtherSpace>();
        foreach (var target in scan.Targets)
        {
            if (spaces.ContainsKey(target.SpaceKey)) continue;
            spaces[target.SpaceKey] = new OtherSpace(
                scan.OthersBySpace.TryGetValue(target.SpaceKey, out var others) ? others : [],
                bounds,
                invisible);
        }
        scan.OthersBySpace.Clear();
        scan.OthersBySpace.TrimExcess();
        return spaces;
    }

    private static void PrintInvisibleOthers(InvisibleCounter invisible, bool verbose)
    {
        var byReason = invisible.Snapshot();
        var total = byReason.Sum(kv => kv.Value);
        if (total == 0) return;
        Console.WriteLine($"  Ignored {total:N0} nearby other-mod objects that are invisible (markers, lights, sounds, decals, trigger boxes, ...).");
        if (!verbose) return;
        foreach (var (reason, count) in byReason)
        {
            Console.WriteLine($"    {reason}: {count:N0}");
        }
    }

    // ------------------------------------------------------------------
    // Same-position/same-size replacement exclusion (rule 2)
    // ------------------------------------------------------------------

    private sealed class ReplacementStats
    {
        public int ExcludedCount { get; set; }
    }

    /// <summary>One rule-2 exclusion, for deterministic verbose logging after the parallel pass.</summary>
    private readonly record struct ReplacementLogEntry(
        FormKey OtherFormKey,
        string? OtherEditorId,
        ModKey OtherPlugin,
        FormKey TargetFormKey,
        string? TargetEditorId,
        float Distance,
        float SizeRatio);

    /// <summary>
    /// Rule 2: an other-mod object is excluded from proximity checks entirely when some target
    /// object in the same space sits within <see cref="RunConfig.ReplacementPositionTolerance"/> of
    /// it and has a similar scaled size (min/max ratio of each matching sorted dimension pair at
    /// least <see cref="RunConfig.ReplacementSizeSimilarity"/>) - it looks like the target plugin
    /// replaced it. Only other objects near a target object are ever measured (grid query per
    /// target, reusing each space's own grid), and each candidate's bounds are resolved at most
    /// once (cached by <see cref="ObjectBoundsProvider"/>). Invisible other objects are never
    /// matched. Matches are found in parallel per target and applied afterwards in target order,
    /// so each excluded object is attributed to its first matching target.
    /// </summary>
    private static ReplacementStats ExcludeReplacedObjects(
        ScanResult scan,
        IReadOnlyDictionary<FormKey, OtherSpace> spaces,
        ObjectBoundsProvider bounds,
        RunConfig config,
        ParallelOptions parallelOptions)
    {
        var stats = new ReplacementStats();
        if (!config.IgnoreReplacedObjects) return stats;

        var tolerance = config.ReplacementPositionTolerance;
        var similarity = config.ReplacementSizeSimilarity;
        var margin = new Vector3(tolerance);
        var targets = scan.Targets;
        var matchesByTarget = new List<(int Index, float Distance, float Ratio)>?[targets.Count];

        Parallel.For(0, targets.Count, parallelOptions, t =>
        {
            var target = targets[t];
            if (!spaces.TryGetValue(target.SpaceKey, out var space) || space.Count == 0) return;

            var targetDims = ScaledSortedDims(bounds.GetLocalBox(target.Base), target.Transform.Scale);
            if (targetDims == null) return; // no bounds: never a replacement match

            var position = target.Transform.Position;
            var candidates = new List<int>();
            space.Grid.Collect(new Box(position - margin, position + margin), candidates);
            if (candidates.Count == 0) return;

            List<(int Index, float Distance, float Ratio)>? matches = null;
            foreach (var index in candidates)
            {
                var other = space[index];
                var distance = Vector3.Distance(other.Position, position);
                if (distance > tolerance) continue;
                if (!space.TryGetVisibleCenter(index, out _)) continue;

                var otherDims = ScaledSortedDims(bounds.GetLocalBox(other.Base), other.Scale);
                if (otherDims == null) continue; // no bounds: never a replacement match

                var ratio = SizeRatio(targetDims.Value, otherDims.Value);
                if (ratio < similarity) continue;

                (matches ??= []).Add((index, distance, ratio));
            }
            matchesByTarget[t] = matches;
        });

        // Each replaced object is attributed to its first matching target in scan order.
        var excludedCount = 0;
        var log = config.Verbose ? new List<ReplacementLogEntry>() : null;
        for (var t = 0; t < targets.Count; t++)
        {
            if (matchesByTarget[t] is not { } matches) continue;
            var target = targets[t];
            var space = spaces[target.SpaceKey];
            foreach (var (index, distance, ratio) in matches)
            {
                if (!space.TryExclude(index)) continue;
                excludedCount++;
                var other = space[index];
                log?.Add(new ReplacementLogEntry(
                    other.FormKey, other.EditorId, other.WinningMod,
                    target.Record.FormKey, target.Record.EditorID,
                    distance, ratio));
            }
        }

        if (log != null)
        {
            foreach (var entry in log.OrderBy(e => e.OtherFormKey.ToString(), StringComparer.Ordinal))
            {
                Console.WriteLine(
                    $"  Ignored replaced object {Describe(entry.OtherFormKey, entry.OtherEditorId)} from {entry.OtherPlugin}: "
                    + $"replaced by {Describe(entry.TargetFormKey, entry.TargetEditorId)}, "
                    + $"distance {entry.Distance:F1}, size ratio {entry.SizeRatio:F2}.");
            }
        }

        stats.ExcludedCount = excludedCount;
        return stats;
    }

    /// <summary>
    /// The local box's scaled dimensions, sorted largest-first, or null when the box has no size at
    /// all (missing bounds - <see cref="ObjectBoundsProvider.GetLocalBox"/> returns <see cref="Box.Zero"/>
    /// for those).
    /// </summary>
    private static (float A, float B, float C)? ScaledSortedDims(Box local, float scale)
    {
        if (local.Size == Vector3.Zero) return null;
        var size = local.Size * scale;
        var dims = new[] { MathF.Abs(size.X), MathF.Abs(size.Y), MathF.Abs(size.Z) };
        Array.Sort(dims);
        return (dims[2], dims[1], dims[0]);
    }

    /// <summary>Smallest, across the three matching sorted-dimension pairs, of min(a,b)/max(a,b).</summary>
    private static float SizeRatio((float A, float B, float C) x, (float A, float B, float C) y) =>
        MathF.Min(MathF.Min(DimRatio(x.A, y.A), DimRatio(x.B, y.B)), DimRatio(x.C, y.C));

    private static float DimRatio(float a, float b)
    {
        if (a <= 0 || b <= 0) return a == b ? 1f : 0f;
        return MathF.Min(a, b) / MathF.Max(a, b);
    }

    /// <summary>Exact too-close test of one grid candidate; a struct so the grid query is allocation-free and inlinable.</summary>
    private readonly struct TooCloseMatcher(OtherSpace space, Box expanded, Vector3 position, Mat3 rotation)
        : IGridMatcher
    {
        public bool IsMatch(int index) =>
            !space.IsExcluded(index)
            && space.TryGetVisibleCenter(index, out var center)
            && expanded.Contains(rotation.TransformTransposed(center - position));
    }

    /// <summary>
    /// Runs the too-close test for every target in parallel. Each target writes only its own
    /// result slot, and hits are returned in target order, so the result (including which other
    /// object is reported first) does not depend on thread scheduling.
    /// </summary>
    private static List<Hit> FindTooCloseTargets(
        IReadOnlyList<TargetObject> targets,
        IReadOnlyDictionary<FormKey, OtherSpace> spaces,
        ObjectBoundsProvider bounds,
        float multiplier,
        ParallelOptions parallelOptions)
    {
        var margin = new Vector3(OtherObjectSearchMargin);
        var matches = new int[targets.Count];

        Parallel.ForEach(Partitioner.Create(0, targets.Count), parallelOptions, range =>
        {
            for (var i = range.Item1; i < range.Item2; i++)
            {
                matches[i] = -1;
                var target = targets[i];
                var space = spaces[target.SpaceKey];
                if (space.Count == 0) continue;

                // Everything about the target (expanded box, query area) is computed once per
                // target here, never per candidate.
                var position = target.Transform.Position;
                var rotation = target.Transform.Rotation;
                var expanded = Geometry.ExpandedLocalBox(bounds.GetLocalBox(target.Base), target.Transform.Scale, multiplier);
                var searchArea = Geometry.WorldAabb(expanded, position, rotation);
                var queryArea = new Box(searchArea.Min - margin, searchArea.Max + margin);

                var matcher = new TooCloseMatcher(space, expanded, position, rotation);
                if (space.Grid.TryFindFirst(queryArea, ref matcher, out var match))
                {
                    matches[i] = match;
                }
            }
        });

        var hits = new List<Hit>();
        for (var i = 0; i < matches.Length; i++)
        {
            if (matches[i] >= 0) hits.Add(new Hit(i, spaces[targets[i].SpaceKey][matches[i]]));
        }
        return hits;
    }

    // ------------------------------------------------------------------
    // Touching clusters
    // ------------------------------------------------------------------

    private sealed class TouchResult
    {
        public List<Removal> Removals { get; } = [];
        public int KeptAsReferenced { get; set; }
        public int Components { get; set; }
        public int ComponentsWithTouching { get; set; }
        public int LargestComponent { get; set; }
        public int CandidatePairs { get; set; }
        public int TouchingPairs { get; set; }
        public int PairsWithoutGeometry { get; set; }
        public VoxelCacheStats Voxels { get; set; }
        public TimeSpan Setup { get; set; }
        public TimeSpan BroadPhase { get; set; }
        public TimeSpan NarrowPhase { get; set; }
        public TimeSpan Clusters { get; set; }
    }

    /// <summary>
    /// Finds every target object connected to a too-close removal through a chain of touching
    /// target objects (same space only), i.e. the connected components of the "touches" graph
    /// that contain a removed object. The graph is explored breadth-first from each removed
    /// object, one level at a time: the broad phase (grid of target world AABBs + oriented box
    /// test, grown by the tolerance) and the narrow phase (exact mesh test) of a level each run in
    /// parallel, and the merge of a level runs in frontier order, so the result is deterministic.
    ///
    /// The touching decision always comes from mesh triangles (<see cref="VoxelMesh.Touches"/>):
    /// a pair where either object has no mesh geometry is never touching. Objects kept because
    /// they are referenced stay and do not propagate (they still support what touches them).
    /// </summary>
    private static TouchResult FindTouchingClusters(
        ScanResult scan,
        IReadOnlyList<Removal> tooClose,
        IReadOnlyList<int> keptTooClose,
        ObjectBoundsProvider bounds,
        RunConfig config,
        ParallelOptions parallelOptions)
    {
        var result = new TouchResult();
        var targets = scan.Targets;
        var tolerance = config.TouchTolerance;
        var timer = Stopwatch.StartNew();

        // Setup: oriented boxes and per-space grids of world AABBs, only for spaces with removals.
        var seedSpaces = tooClose.Select(r => targets[r.TargetIndex].SpaceKey).ToHashSet();
        var boxes = new OrientedBox[targets.Count];
        Parallel.ForEach(Partitioner.Create(0, targets.Count), parallelOptions, range =>
        {
            for (var i = range.Item1; i < range.Item2; i++)
            {
                if (!seedSpaces.Contains(targets[i].SpaceKey)) continue;
                boxes[i] = OrientedBox.FromLocal(bounds.GetLocalBox(targets[i].Base), targets[i].Transform);
            }
        });

        var members = new Dictionary<FormKey, List<int>>();
        for (var i = 0; i < targets.Count; i++)
        {
            if (!seedSpaces.Contains(targets[i].SpaceKey)) continue;
            if (!members.TryGetValue(targets[i].SpaceKey, out var list))
            {
                list = [];
                members[targets[i].SpaceKey] = list;
            }
            list.Add(i);
        }
        var grids = new Dictionary<FormKey, (SpatialGrid Grid, List<int> Members)>();
        foreach (var (spaceKey, list) in members)
        {
            var aabbs = list.Select(i => boxes[i].WorldAabb(tolerance)).ToArray();
            grids[spaceKey] = (SpatialGrid.FromBoxes(aabbs), list);
        }
        result.Setup = timer.Elapsed;

        var voxels = new VoxelCache(config.VoxelSize, bounds.ReadGeometry);
        var isSeed = new bool[targets.Count];
        foreach (var removal in tooClose) isSeed[removal.TargetIndex] = true;
        // Too-close objects that were kept as referenced stay, are already logged and counted,
        // and do not propagate: mark them visited up front.
        var visited = new bool[targets.Count];
        foreach (var index in keptTooClose) visited[index] = true;
        var pairsWithoutGeometry = 0;

        var broadTimer = new Stopwatch();
        var narrowTimer = new Stopwatch();
        var clusterTimer = Stopwatch.StartNew();

        foreach (var seed in tooClose.Select(r => r.TargetIndex))
        {
            // A seed reached from an earlier seed already belongs to that seed's component.
            if (visited[seed]) continue;
            visited[seed] = true;

            var componentSize = 1;
            var frontier = new List<int> { seed };
            while (frontier.Count > 0)
            {
                // Broad phase: unvisited targets whose grown oriented box overlaps.
                broadTimer.Start();
                var candidates = new List<int>[frontier.Count];
                Parallel.For(0, frontier.Count, parallelOptions, () => (Scratch: new List<int>(), Seen: new HashSet<int>()), (f, _, local) =>
                {
                    var node = frontier[f];
                    var (grid, list) = grids[targets[node].SpaceKey];
                    local.Scratch.Clear();
                    local.Seen.Clear();
                    grid.Collect(boxes[node].WorldAabb(tolerance), local.Scratch);
                    var found = new List<int>();
                    foreach (var slot in local.Scratch)
                    {
                        var other = list[slot];
                        if (other == node || visited[other] || !local.Seen.Add(other)) continue;
                        if (boxes[node].Intersects(boxes[other], tolerance)) found.Add(other);
                    }
                    found.Sort();
                    candidates[f] = found;
                    return local;
                }, _ => { });

                // Pairs grouped by target node, groups and pairs in frontier order.
                var pairs = new List<(int From, int To)>();
                var groups = new List<List<int>>();
                var groupOf = new Dictionary<int, int>();
                for (var f = 0; f < frontier.Count; f++)
                {
                    foreach (var other in candidates[f])
                    {
                        if (!groupOf.TryGetValue(other, out var group))
                        {
                            group = groups.Count;
                            groupOf[other] = group;
                            groups.Add([]);
                        }
                        groups[group].Add(pairs.Count);
                        pairs.Add((frontier[f], other));
                    }
                }
                broadTimer.Stop();
                result.CandidatePairs += pairs.Count;

                // Narrow phase: exact mesh test, per target node only until one pair touches.
                narrowTimer.Start();
                var touchingPair = new int[groups.Count];
                Parallel.For(0, groups.Count, parallelOptions, g =>
                {
                    touchingPair[g] = -1;
                    foreach (var k in groups[g])
                    {
                        var (from, to) = pairs[k];
                        var fromPath = bounds.GetMeshPath(targets[from].Base);
                        var toPath = bounds.GetMeshPath(targets[to].Base);
                        var fromMesh = fromPath == null ? null : voxels.Get(fromPath);
                        var toMesh = fromMesh == null || toPath == null ? null : voxels.Get(toPath);
                        if (fromMesh == null || toMesh == null)
                        {
                            Interlocked.Increment(ref pairsWithoutGeometry);
                            continue;
                        }
                        // Iterate the mesh with fewer voxels; look up in the one with more.
                        var touches = fromMesh.VoxelCount >= toMesh.VoxelCount
                            ? VoxelMesh.Touches(fromMesh, targets[from].Transform, toMesh, targets[to].Transform, tolerance)
                            : VoxelMesh.Touches(toMesh, targets[to].Transform, fromMesh, targets[from].Transform, tolerance);
                        if (touches)
                        {
                            touchingPair[g] = k;
                            break;
                        }
                    }
                });
                narrowTimer.Stop();

                // Merge in pair order (deterministic).
                var touchingPairs = touchingPair.Where(k => k >= 0).Order().ToList();
                var next = new List<int>();
                foreach (var k in touchingPairs)
                {
                    result.TouchingPairs++;
                    var (from, to) = pairs[k];
                    if (visited[to]) continue;
                    visited[to] = true;

                    if (isSeed[to])
                    {
                        // Another too-close removal: same component, already removed.
                        componentSize++;
                        next.Add(to);
                        continue;
                    }

                    var keepReason = config.SkipReferenced ? GetKeepReason(targets[to], scan.TargetReferences) : null;
                    if (keepReason != null)
                    {
                        result.KeptAsReferenced++;
                        Console.WriteLine(
                            $"  Kept {Describe(targets[to].Record)} in {scan.SpaceNames[targets[to].SpaceKey]}: {keepReason} "
                            + $"(touches removed {Describe(targets[from].Record)}).");
                        continue;
                    }

                    result.Removals.Add(new Removal(to, Other: null, TouchedIndex: from));
                    componentSize++;
                    next.Add(to);
                }
                frontier = next;
            }

            result.Components++;
            if (componentSize > 1) result.ComponentsWithTouching++;
            result.LargestComponent = Math.Max(result.LargestComponent, componentSize);
        }

        clusterTimer.Stop();
        result.PairsWithoutGeometry = pairsWithoutGeometry;
        result.BroadPhase = broadTimer.Elapsed;
        result.NarrowPhase = narrowTimer.Elapsed;
        result.Clusters = clusterTimer.Elapsed - broadTimer.Elapsed - narrowTimer.Elapsed;
        result.Voxels = voxels.GetStats();
        return result;
    }

    private static string? GetKeepReason(TargetObject target, IReadOnlyDictionary<FormKey, string> references)
    {
        if (target.IsTeleportDoor) return "teleport door";
        return references.TryGetValue(target.Record.FormKey, out var reason) ? reason : null;
    }

    // ------------------------------------------------------------------
    // Removal
    // ------------------------------------------------------------------

    /// <summary>
    /// Disables the object: sets the Initially Disabled flag and moves it to Z = -30000 (X/Y kept).
    /// An existing Enable Parent would override the flag, so it is replaced by the player with
    /// "set enable state to opposite of parent" (as xEdit's "Undelete and Disable References"
    /// does). Mirrors what Mutagen's own placed-record context does: override the winning cell
    /// (without its children), then add a copy of the winning placed record to the same child
    /// list (persistent or temporary) it was found in. <paramref name="placedByList"/> caches a
    /// FormKey lookup per overridden child list. Returns true when an Enable Parent was replaced.
    /// </summary>
    private static bool RemoveObject(
        TargetObject target,
        ISkyrimMod patchMod,
        Dictionary<object, Dictionary<FormKey, IPlaced>> placedByList)
    {
        var cell = target.WinningCell.GetOrAddAsOverride(patchMod);
        var list = target.InPersistentList ? cell.Persistent : cell.Temporary;
        if (!placedByList.TryGetValue(list, out var byFormKey))
        {
            byFormKey = new Dictionary<FormKey, IPlaced>();
            foreach (var existing in list) byFormKey.TryAdd(existing.FormKey, existing);
            placedByList[list] = byFormKey;
        }

        var formKey = target.Record.FormKey;
        if (!byFormKey.TryGetValue(formKey, out var placed))
        {
            placed = (IPlaced)target.Record.DeepCopy();
            list.Add(placed);
            byFormKey[formKey] = placed;
        }

        placed.MajorRecordFlagsRaw |= (int)SkyrimMajorRecord.SkyrimMajorRecordFlag.InitiallyDisabled;
        if (placed.Placement is { } placement)
        {
            placement.Position = new P3Float(placement.Position.X, placement.Position.Y, RemovedZ);
        }

        if (placed.EnableParent == null) return false;
        placed.EnableParent = new EnableParent
        {
            Reference = new FormLink<IPlacedGetter>(PlayerRef),
            Flags = EnableParent.Flag.SetEnableStateToOppositeOfParent,
        };
        return true;
    }

    // ------------------------------------------------------------------
    // Logging
    // ------------------------------------------------------------------

    private static string Describe(IMajorRecordGetter record) => Describe(record.FormKey, record.EditorID);

    private static string Describe(FormKey formKey, string? editorId) =>
        string.IsNullOrEmpty(editorId) ? formKey.ToString() : $"{editorId} [{formKey}]";

    /// <summary>
    /// Base objects are resolved through their typed base link (already cached by the bounds
    /// lookup), never through an untyped IMajorRecordGetter lookup.
    /// </summary>
    private static string DescribeBase(ObjectBoundsProvider bounds, BaseRef? baseRef)
    {
        if (baseRef is not { } reference) return "(none)";
        return bounds.TryResolveBase(reference) is { } record ? Describe(record) : reference.FormKey.ToString();
    }

    private static void LogRemoval(ObjectBoundsProvider bounds, ScanResult scan, Removal removal)
    {
        var target = scan.Targets[removal.TargetIndex];
        var location = target.CellName == null
            ? scan.SpaceNames[target.SpaceKey]
            : $"{scan.SpaceNames[target.SpaceKey]}, cell {target.CellName}";
        string reason;
        if (removal.Other is { } other)
        {
            reason = $"too close to {Describe(other.FormKey, other.EditorId)} from {other.FormKey.ModKey}"
                + (other.WinningMod == other.FormKey.ModKey ? string.Empty : $" (winning override in {other.WinningMod})");
        }
        else if (removal.TouchedIndex is { } touched)
        {
            reason = $"touches removed {Describe(scan.Targets[touched].Record)}";
        }
        else
        {
            reason = "removed";
        }
        Console.WriteLine($"  Removed {Describe(target.Record)} (base {DescribeBase(bounds, target.Base)}) in {location}; {reason}");
    }

    private static void PrintTouchStats(TouchResult touch)
    {
        Console.WriteLine(
            $"Touching objects: {touch.Removals.Count:N0} removed in {touch.Components:N0} components "
            + $"({touch.ComponentsWithTouching:N0} with touching objects, largest {touch.LargestComponent:N0} removed objects); "
            + $"{touch.KeptAsReferenced:N0} kept as referenced.");
        var voxels = touch.Voxels;
        Console.WriteLine(
            $"  Pairs: {touch.CandidatePairs:N0} box candidates, {touch.TouchingPairs:N0} touching, "
            + $"{touch.PairsWithoutGeometry:N0} skipped without mesh geometry (never touching).");
        Console.WriteLine(
            $"  Meshes voxelized: {voxels.Built:N0} ({voxels.Voxels:N0} voxels, {voxels.Samples:N0} samples"
            + (voxels.Coarsened > 0 ? $", {voxels.Coarsened:N0} sampled coarser due to size" : string.Empty)
            + (voxels.TooLarge > 0 ? $", {voxels.TooLarge:N0} over {VoxelMesh.MaxSamples:N0} samples even when coarsest, not used" : string.Empty)
            + $"); peak resident {voxels.PeakResidentMeshes:N0} meshes, ~{voxels.PeakResidentBytes / (1024.0 * 1024.0):N0} MB"
            + (voxels.Evicted > 0 ? $"; {voxels.Evicted:N0} evicted, {voxels.Rebuilt:N0} rebuilt" : string.Empty) + ".");
        Console.WriteLine(
            $"  Timing: setup {touch.Setup.TotalSeconds:F1}s, broad phase {touch.BroadPhase.TotalSeconds:F1}s, "
            + $"narrow phase {touch.NarrowPhase.TotalSeconds:F1}s, clusters {touch.Clusters.TotalSeconds:F1}s.");
    }

    private static void PrintBoundsStats(ObjectBoundsProvider bounds, bool useNif)
    {
        if (useNif)
        {
            Console.WriteLine(
                $"Bounds: {bounds.BasesFromNif:N0} bases from NIF, {bounds.BasesNifFallbackToObnd:N0} NIF misses, "
                + $"{bounds.BasesFromObnd:N0} from OBND, {bounds.BasesWithoutBounds + bounds.BasesUnresolved:N0} without bounds. "
                + $"Meshes: {bounds.ModelsRead:N0} read, {bounds.ModelsFailed:N0} failed "
                + $"({bounds.ModelsFromLooseFiles:N0} loose, {bounds.ModelsFromArchives:N0} from {bounds.ArchivesIndexed:N0} archives).");
        }
        else
        {
            Console.WriteLine(
                $"Bounds: {bounds.BasesFromObnd:N0} bases from OBND, "
                + $"{bounds.BasesWithoutBounds + bounds.BasesUnresolved:N0} without bounds.");
        }
    }

    private static void PrintSpaceSummary(
        ScanResult scan,
        IReadOnlyDictionary<FormKey, OtherSpace> spaces,
        IReadOnlyList<Removal> removed)
    {
        var removedBySpace = removed
            .GroupBy(r => scan.Targets[r.TargetIndex].SpaceKey)
            .ToDictionary(g => g.Key, g => g.Count());
        Console.WriteLine("Per cell/worldspace (target objects / other objects / removed):");
        foreach (var group in scan.Targets
                     .GroupBy(t => t.SpaceKey)
                     .OrderBy(g => scan.SpaceNames[g.Key], StringComparer.OrdinalIgnoreCase))
        {
            removedBySpace.TryGetValue(group.Key, out var removedCount);
            Console.WriteLine(
                $"  {scan.SpaceNames[group.Key]}: {group.Count():N0} / {spaces[group.Key].Count:N0} / {removedCount:N0}");
        }
    }
}
