using System.Diagnostics;
using System.Reflection;
using AddedObjectRemover.Run.RunAllSteps;
using AddedObjectRemover.Run.RunAllSteps.Contracts;
using AddedObjectRemover.Steps.BuildLogAndReports;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Synthesis.Settings;

namespace AddedObjectRemover;

public static class Program
{
    internal static readonly SettingsSchema SettingsSchema = new(
        typeof(Settings), property => property.GetCustomAttribute<SynthesisSettingName>()?.Name);

    public static async Task<int> Main(string[] args)
    {
        using var logFile = ConsoleLogFile.StartIfRequested(ref args);
        try
        {
            return await SynthesisPipeline.Instance
                .SetAutogeneratedSettings(
                    "Settings",
                    "settings.json",
                    out Lazy<Settings> lazySettings)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(
                    state => RunPatch(state, () => LoadSettings(lazySettings), Environment.ProcessorCount))
                .SetTypicalOpen(GameRelease.SkyrimSE, "AddedObjectRemover.esp")
                .Run(args);
        }
        catch (Exception ex) when (logFile != null)
        {
            logFile.WriteToFileOnly(ex.ToString());
            throw;
        }
    }

    /// <param name="loadSettings">Called after the banner, so a settings failure message follows it.</param>
    internal static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, Func<Settings> loadSettings, int workers)
    {
        var totalTimer = Stopwatch.StartNew();
        Console.WriteLine("=== Added Object Remover ===");

        var settings = loadSettings();
        var plugins = LoadOrderPluginsReader.Read(state.LoadOrder, state.PatchMod.ModKey);
        var pluginRecords = new PluginRecordsFactory(state.LoadOrder, state.LinkCache, state.PatchMod);
        var request = RunSettingsValidation.Build(settings, pluginRecords.Open(), plugins, state.OutputPath.Path, workers);
        var environment = new RunEnvironment(
            plugins,
            pluginRecords,
            new MeshFilesFactory(
                state.DataFolderPath.Path, state.GameRelease, [.. state.LoadOrder.ListedOrder.Select(listing => listing.ModKey)]),
            new BaseFactsReader(state.LinkCache),
            new ConsoleLogSink(),
            new CsvReportOutput(),
            () => totalTimer.Elapsed);
        RunAllSteps.Run(request, environment);
    }

    private static Settings LoadSettings(Lazy<Settings> lazySettings)
    {
        try
        {
            return SettingsLoading.Load(() => lazySettings.Value, SettingsSchema);
        }
        catch (SettingsUnreadableException ex)
        {
            Console.Error.WriteLine(ex.Message);
            throw;
        }
    }
}
