using System.Diagnostics;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;

namespace AddedObjectRemover;

public static class Program
{
    private static Lazy<Settings> _lazySettings = null!;

    public static async Task<int> Main(string[] args)
    {
        using var logFile = ConsoleLogFile.StartIfRequested(ref args);
        try
        {
            return await SynthesisPipeline.Instance
                .SetAutogeneratedSettings(
                    "Settings",
                    "settings.json",
                    out _lazySettings)
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetTypicalOpen(GameRelease.SkyrimSE, "AddedObjectRemover.esp")
                .Run(args);
        }
        catch (Exception ex) when (logFile != null)
        {
            logFile.WriteToFileOnly(ex.ToString());
            throw;
        }
    }

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state) =>
        RunPatch(state, LoadSettings, Environment.ProcessorCount);

    /// <param name="loadSettings">Called after the banner, so a settings failure message follows it.</param>
    internal static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state, Func<Settings> loadSettings, int workers)
    {
        var totalTimer = Stopwatch.StartNew();
        Console.WriteLine("=== Added Object Remover ===");

        var settings = loadSettings();
        var mods = ModFactsReader.Read(state);
        var config = RunConfigFactory.Create(settings, mods, state.OutputPath.Path);
        if (config == null) return;
        var standing = Standing.Decide(mods, config.Standing);
        DiagnosticsFiles.DeleteEarlierFiles(config.DiagnosticsFolder, config.WritesDiagnostics);
        RunReport.PrintConfig(config, mods, standing);

        new RemovalPipeline(state, config, mods, standing, workers).Run(totalTimer);
    }

    /// <summary>Settings are read lazily from settings.json; an invalid saved value throws here on first access.</summary>
    private static Settings LoadSettings()
    {
        try
        {
            return _lazySettings.Value;
        }
        catch (JsonException ex)
        {
            var message = SettingsFailureMessage.Describe(ex);
            Console.Error.WriteLine(message);
            throw new InvalidOperationException(message, ex);
        }
    }
}
